---
title: "COD-PS Availability"
date: ''
output:
  html_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
#install.packages("googlesheets4") ## working with CRAN version of googlesheets4, not the dev version on GitHub
library(googlesheets4)
library(tidyverse)
library(ggrepel)
library(treemap)
library(scales)
library(gridExtra)
# names of key columns in Google Sheet
var_name_action <- "UNFPA - recommended action"
var_name_region <- "UNFPA Region"
var_name_country_type <- "Type"
```

```{r "load_data", echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
our_url <- "https://docs.google.com/spreadsheets/d/1hjI8synLx3yfjTvfLBKgQc3Hj-XU_Lhoww_DxUTe59A/edit#gid=0"

our_data_for_names <- read_sheet(ss=our_url,
                                 skip=8)
names(our_data_for_names)
our_data <- read_sheet(ss=our_url,
                       skip=10) %>%
            as.data.frame()
names(our_data) <- names(our_data_for_names)
## re-code missing values more descriptive values
our_data[is.na(our_data[, var_name_action]), 
         var_name_action] <- "(Action not specified)"
our_data[is.na(our_data[, var_name_region]), 
         var_name_region] <- "(Region not specified)"
our_data[is.na(our_data[, var_name_country_type]), 
         var_name_country_type] <- "(Type not specified)"
```

```{r "function_table_recommended_action_global", echo=FALSE, warning=FALSE, message=FALSE}
get_table_recommended_action <- function(data,
                                         var.name.action,
                                         var.name.region,
                                         var.name.country.type,
                                         specific.region=NULL,
                                         specific.country.type=NULL) {
# restrict data to a single region, if specified
if (is.null(specific.region) == FALSE) {
  stopifnot(var.name.region %in% names(data))
  stopifnot(specific.region %in% unique(data[, var.name.region]))
  data <- data[data[, var.name.region] == specific.region, ] 
}
if (is.null(specific.country.type) == FALSE) {
  stopifnot(var.name.country.type %in% names(data))
  stopifnot(specific.country.type %in% unique(data[, var.name.country.type]))
  data <- data[data[, var.name.country.type] == specific.country.type, ] 
}
table_recommended_action <- as.data.frame(table(data[, var.name.action])) 
                                                #useNA="always"))
table_recommended_action <- table_recommended_action %>% rename("action"="Var1",
                                                                "count"="Freq")
table_recommended_action$count <- as.integer(table_recommended_action$count)
# sort categories by descending frequency
test <- table_recommended_action %>%
#          arrange(desc(count)) %>%
          select(action) %>%
          pull() %>%
          as.character()
table_recommended_action$action <- factor(as.character(table_recommended_action$action),
                                          levels=test)
# save specific colors to be consistent across plots
table_recommended_action$color <- hcl.colors(length(levels(table_recommended_action$action)),
                                             "Dark2")
return(table_recommended_action)
}

```

```{r "function_lollipop", echo=FALSE, warning=FALSE, message=FALSE}
get_lollipop <- function(data,
                         name.action,
                         name.count) {
g_global <- ggplot(data,
                   aes_string(x=name.action,
                              y=name.count))
g_global <- g_global + 
            geom_point(size=2) +
            geom_segment(aes_string(x=name.action,
                                    xend=name.action,
                                    y=0,
                                    yend=name.count)) +
            scale_y_continuous(breaks= pretty_breaks()) +
            labs(x="UNFPA Recommended Action",
                 y="Count") +
            theme_classic() + 
            theme(axis.text.x=element_text(size=8))
return(g_global)
}
```

```{r "function_treemap_plot_global", echo=FALSE, warning=FALSE, message=FALSE}
get_treemap <- function(data,
                        name.action,
                        name.count) {
n_countries <- sum(data[, name.count], 
                   na.rm=TRUE)
data$percentage <- data[, name.count] / n_countries
data$action_and_count <- paste0(data[, name.action],
                                "\n",
                                data[, name.count],
                                " (",
                                round(100 * data$percentage, 
                                      0),
                                     "%)")
treemap(data,
            # data
            index="action_and_count",
            vSize=name.count,
            type="index",
            
            # Main
            title="",
            palette="Dark2",

            # Borders:
            border.col=c("black"),             
            border.lwds=1,                         
        
            # Labels
            fontsize.labels=12,
            fontcolor.labels="white",
            fontface.labels=1,            
            bg.labels=c("transparent"),              
            align.labels=c("left", "top"),                                  
            overlap.labels=0.5,
            inflate.labels=FALSE)
}
```


```{r "function_donut_plot_global", echo=FALSE, warning=FALSE, message=FALSE}
# Donut plots are not provided by ggplot2 or base R so I am hacking it together with this guide:
# https://www.r-graph-gallery.com/128-ring-or-donut-plot.html, sinice donut plots have to be
get_donut <- function(data,
                      data_global,
                      name.action,
                      name.count,
                      title="") {
# Compute percentages
data$fraction <- data[, name.count] / sum(data[, name.count], 
                                          na.rm=TRUE)
data$percentage <- round(data$fraction * 100, 0)

# Merge in colors from global data
data$color <- NULL
k <- left_join(x=data,
               y=data_global[, c(name.action, "color")],
               by="action")
data$color <- k$color

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data[, name.action],
                    "\n", 
                     data[, name.count],
                     " (",
                     data$percentage,
                     "%)")

# Make the plot
g_donut <- ggplot(data, 
       aes(ymax=ymax, 
           ymin=ymin, 
           xmax=4, 
           xmin=3, 
           fill=action)) +
  geom_rect(alpha=0.8) +
  geom_text_repel(x=5.2, 
            col="black",
            aes(y=labelPosition, 
                label=label, 
                color=action), 
            force=0.9,
            segment.size=0,
            segment.alpha=0,
            fontface="bold",
            size=3) + # x here controls label position (inner / outer) +
  scale_fill_manual("asdf",
                    values=data$color) +
  #scale_fill_brewer(palette="Dark2") +
  #scale_color_brewer(palette="Dark2") +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none") + 
  theme(plot.margin=unit(c(1, 1, 1, 1),"cm")) +
  theme(plot.title = element_text(hjust=0.5,
                                  vjust=8,
                                  size=16,
                                  face="bold")) +
  ggtitle(title)
return(g_donut)
}
```

# Global plots of UNFPA recommended action
```{r, "get_data_global", echo=FALSE, warning=FALSE, message=FALSE}
table_action_global <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type)
```

```{r, "donut_plot", echo=FALSE, warning=FALSE, message=FALSE}
get_donut(data=table_action_global,
          data_global=table_action_global, # (messy but just hacking together for now to merge colors)
          name.action="action",
          name.count="count")
```

# Country-type plots of UNFPA recommended action
```{r, "get_data_type", echo=FALSE, warning=FALSE, message=FALSE}
table_action_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.country.type="O")
table_action_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.country.type="P")
```

```{r, "donut_plots_by_type", echo=FALSE, warning=FALSE, message=FALSE}
donut_P <- get_donut(data=table_action_P,
                     data_global=table_action_global,
          name.action="action",
          name.count="count",
          title="Preparedness \nCountries")
donut_O <- get_donut(data=table_action_O,
                     data_global=table_action_global,
          name.action="action",
          name.count="count",
          title="Operational Response \nCountries")
grid.arrange(donut_P,
           donut_O,
           nrow=1,
           ncol=2)
```

# Regional plots of UNFPA recommended action
```{r, "get_data_regional", echo=FALSE, warning=FALSE, message=FALSE}
# APRO
table_action_APRO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="APRO",
                             specific.country.type="P")
table_action_APRO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="APRO",
                             specific.country.type="O")
# ASRO
table_action_ASRO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="ASRO",
                             specific.country.type="P")
table_action_ASRO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="ASRO",
                             specific.country.type="O")
# EECARO
table_action_EECARO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="EECARO",
                             specific.country.type="P")
table_action_EECARO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="EECARO",
                             specific.country.type="O")
# ESARO
table_action_ESARO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="ESARO",
                             specific.country.type="P")
table_action_ESARO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="ESARO",
                             specific.country.type="O")
# LACRO
table_action_LACRO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="LACRO",
                             specific.country.type="P")
table_action_LACRO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="LACRO",
                             specific.country.type="O")
# WCARO
table_action_WCARO_P <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="WCARO",
                             specific.country.type="P")
table_action_WCARO_O <- get_table_recommended_action(data=our_data,
                             var.name.action=var_name_action,
                             var.name.region=var_name_region,
                             var.name.country.type=var_name_country_type,
                             specific.region="WCARO",
                             specific.country.type="O")

```

## APRO
```{r, "donut_plot_APRO", echo=FALSE, warning=FALSE, message=FALSE}
donut_APRO_P <- get_donut(data=table_action_APRO_P,
                          data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_APRO_O <- get_donut(data=table_action_APRO_O,
                          data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_APRO_P,
             donut_APRO_O,
             nrow=1,
             ncol=2)
```

## ASRO
```{r, "donut_plot_ASRO", echo=FALSE, warning=FALSE, message=FALSE}
donut_ASRO_P <- get_donut(data=table_action_ASRO_P,
                          data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_ASRO_O <- get_donut(data=table_action_ASRO_O,
                          data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_ASRO_P,
             donut_ASRO_O,
             nrow=1,
             ncol=2)
```

## EECARO
```{r, "donut_plot_EECARO", echo=FALSE, warning=FALSE, message=FALSE}
donut_EECARO_P <- get_donut(data=table_action_EECARO_P,
                            data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_EECARO_O <- get_donut(data=table_action_EECARO_O,
                            data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_EECARO_P,
             donut_EECARO_O,
             nrow=1,
             ncol=2)
```

## ESARO
```{r, "donut_plot_ESARO", echo=FALSE, warning=FALSE, message=FALSE}
donut_ESARO_P <- get_donut(data=table_action_ESARO_P,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_ESARO_O <- get_donut(data=table_action_ESARO_O,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_ESARO_P,
             donut_ESARO_O,
             nrow=1,
             ncol=2)
```

## LACRO
```{r, "donut_plot_LACRO", echo=FALSE, warning=FALSE, message=FALSE}
donut_LACRO_P <- get_donut(data=table_action_LACRO_P,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_LACRO_O <- get_donut(data=table_action_LACRO_O,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_LACRO_P,
             donut_LACRO_O,
             nrow=1,
             ncol=2)
```

## WCARO
```{r, "donut_plot_WCARO", echo=FALSE, warning=FALSE, message=FALSE}
donut_WCARO_P <- get_donut(data=table_action_WCARO_P,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Preparedness \nCountries")
donut_WCARO_O <- get_donut(data=table_action_WCARO_O,
                           data_global=table_action_global,
                          name.action="action",
                          name.count="count",
                          title="Operational Response \nCountries")
grid.arrange(donut_WCARO_P,
             donut_WCARO_O,
             nrow=1,
             ncol=2)
```
